spring.application.name=eventplanner
spring.security.user.name=test
spring.security.user.password=test
jwt.secret=korisnickoime

spring.config.import=\
  file:../external.properties

# External properties should include:
#  Database properties:
#    db.url, db.username, db.password, db.driver-class-name
#
#  Mail properties:
#    spring.mail.host, spring.mail.port,
#    spring.mail.username, spring.mail.password
#    spring.mail.properties.mail.smtp.auth,
#    spring.mail.properties.mail.smtp.starttls.enable,
#    spring.mail.properties.mail.transport.protocol
#
#  Frontend properties:
#    frontend.url

# JPA/Hibernate Configuration
jpa.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.show-sql=true
jpa.ddl-auto=update

spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false