spring.application.name=eventplanner
spring.security.user.name=test
spring.security.user.password=test
jwt.secret=korisnickoime

spring.config.import=file:../db.properties

# JPA/Hibernate Configuration
jpa.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.show-sql=true
jpa.ddl-auto=update
