spring.application.name=eventplanner
spring.security.user.name=test
spring.security.user.password=test
jwt.secret=korisnickoime

suspension.period.days=3
log.endpoints.enabled=false


spring.config.import=\
  file:../external.properties

# External properties should include:
#  Database properties:
#    db.url, db.username, db.password, db.driver-class-name
#
#  Mail properties:
#    spring.mail.host, spring.mail.port,
#    spring.mail.username, spring.mail.password
#    spring.mail.properties.mail.smtp.auth,
#    spring.mail.properties.mail.smtp.starttls.enable,
#    spring.mail.properties.mail.transport.protocol
#
#  Frontend properties:
#    frontend.url
#
#  Uploads properties:
#    uploads.dir

# JPA/Hibernate Configuration
jpa.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.show-sql=true
jpa.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false